name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v4

      - name: Устанавливаем Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Устанавливаем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Принимаем лицензии и устанавливаем SDK
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "build-tools;33.0.2" \
            "platforms;android-33"

      - name: Устанавливаем зависимости
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install buildozer==1.5.0 cython==0.29.33

      - name: Собираем APK
        run: |
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROIDNDK=$ANDROID_NDK_ROOT
          export ANDROIDAPI=33
          export ANDROIDMINAPI=21
          buildozer android debug

      - name: Сохраняем APK
        uses: actions/upload-artifact@v4
        with:
          name: autoconspect-apk
          path: bin/*.apk
